"""
Power flow accuracy tests for Case33bw (33-bus Baran & Wu distribution network).

Validates the Forward-Backward Sweep (FBS) implementation against:
  1. Known literature values — Baran & Wu (1989), IEEE Trans. Power Delivery
       P_loss  ≈ 202.67 kW
       Q_loss  ≈ 135.14 kVAr
       V_min   ≈ 0.9131 p.u. at bus 18
  2. MATPOWER Newton-Raphson results (optional) — generated by
       powerzoo/case/source_mfile/run_my_pf.m
       Saved to tests/ref_data/case33bw_bus.csv  and  case33bw_branch.csv
"""
import os

import numpy as np
import pandas as pd
import pytest

# ── Reference file paths (MATPOWER) ─────────────────────────────────────────
REF_DIR          = os.path.join(os.path.dirname(__file__), 'ref_data')
MATPOWER_BUS_CSV = os.path.join(REF_DIR, 'case33bw_bus.csv')
MATPOWER_BR_CSV  = os.path.join(REF_DIR, 'case33bw_branch.csv')
HAS_MATPOWER     = os.path.exists(MATPOWER_BUS_CSV)

# ── Literature constants (Baran & Wu, 1989, base case) ───────────────────────
LIT_P_LOSS_MW    = 0.20267   # 202.67 kW
LIT_Q_LOSS_MVAR  = 0.13514   # 135.14 kVAr
LIT_V_MIN_PU     = 0.9131    # minimum bus voltage
LIT_V_MIN_BUS_0  = 17        # 0-based index of worst bus (bus 18 in 1-indexed)


# ── Shared fixture ────────────────────────────────────────────────────────────
@pytest.fixture(scope='module')
def pf():
    """Run FBS power flow once; share results across all tests in this module."""
    from powerzoo.envs.grid.dist import DistGridEnv
    env = DistGridEnv()
    nodes, lines = env.cal_pf(df=True)
    return env, nodes, lines


# ── Convergence ───────────────────────────────────────────────────────────────
class TestConvergence:
    def test_converges(self, pf):
        env, nodes, lines = pf
        assert env._converged, 'FBS did not converge'

    def test_iterations_in_range(self, pf):
        env, nodes, lines = pf
        assert 1 <= env._iterations <= 10, \
            f'Expected 1–10 iterations, got {env._iterations}'


# ── Bus voltages ──────────────────────────────────────────────────────────────
class TestBusVoltages:
    def test_slack_bus_is_1pu(self, pf):
        env, nodes, lines = pf
        np.testing.assert_allclose(nodes['v_mag'].iloc[0], 1.0, atol=1e-10)

    def test_all_voltages_positive(self, pf):
        env, nodes, lines = pf
        assert np.all(nodes['v_mag'].values > 0)

    def test_no_voltage_exceeds_slack(self, pf):
        """Passive radial network: no bus voltage can exceed the slack."""
        env, nodes, lines = pf
        assert np.all(nodes['v_mag'].values <= 1.0 + 1e-6)

    def test_min_voltage_at_correct_bus(self, pf):
        """Worst bus is bus 18 (0-indexed: 17) per Baran & Wu (1989)."""
        env, nodes, lines = pf
        assert nodes['v_mag'].values.argmin() == LIT_V_MIN_BUS_0

    def test_min_voltage_vs_literature(self, pf):
        """V_min within 0.002 p.u. of Baran & Wu (1989) value (0.9131 p.u.)."""
        env, nodes, lines = pf
        v_min = nodes['v_mag'].min()
        assert abs(v_min - LIT_V_MIN_PU) < 0.002, \
            f'V_min = {v_min:.6f} p.u.  (literature: {LIT_V_MIN_PU})'

    def test_main_feeder_voltage_decreases_monotonically(self, pf):
        """Buses 0–17 form the main feeder; voltage must decrease at each step."""
        env, nodes, lines = pf
        v_main = nodes['v_mag'].values[:18]   # slack + 17 downstream buses
        diffs = np.diff(v_main)
        bad = diffs[diffs > 1e-8]
        assert len(bad) == 0, \
            f'Non-monotonic voltage drop on main feeder: {bad}'


# ── Line losses ───────────────────────────────────────────────────────────────
class TestLineLosses:
    def test_p_loss_vs_literature(self, pf):
        """Total P_loss within 2 kW of Baran & Wu (1989) (202.67 kW)."""
        env, nodes, lines = pf
        p_loss = lines['p_loss_MW'].sum()
        assert abs(p_loss - LIT_P_LOSS_MW) < 0.002, \
            f'P_loss = {p_loss*1e3:.2f} kW  (literature: {LIT_P_LOSS_MW*1e3:.2f} kW)'

    def test_q_loss_vs_literature(self, pf):
        """Total Q_loss within 2 kVAr of Baran & Wu (1989) (135.14 kVAr)."""
        env, nodes, lines = pf
        q_loss = lines['q_loss_MVAr'].sum()
        assert abs(q_loss - LIT_Q_LOSS_MVAR) < 0.002, \
            f'Q_loss = {q_loss*1e3:.2f} kVAr  (literature: {LIT_Q_LOSS_MVAR*1e3:.2f} kVAr)'

    def test_all_line_p_losses_non_negative(self, pf):
        """Resistive network: every line active loss must be ≥ 0."""
        env, nodes, lines = pf
        assert np.all(lines['p_loss_MW'].values >= -1e-8)

    def test_all_line_q_losses_non_negative(self, pf):
        """Inductive network (X > 0): every line reactive loss must be ≥ 0."""
        env, nodes, lines = pf
        assert np.all(lines['q_loss_MVAr'].values >= -1e-8)

    def test_power_conservation(self, pf):
        """Feeder-head flow ≈ total load + total losses (within 1%)."""
        env, nodes, lines = pf
        p_head  = lines['p_flow_MW'].iloc[0]
        p_load  = env._get_node_loads_p().sum()
        p_loss  = lines['p_loss_MW'].sum()
        np.testing.assert_allclose(
            p_head, p_load + p_loss, rtol=0.01,
            err_msg=(f'Feeder-head flow {p_head:.4f} MW ≠ '
                     f'load ({p_load:.4f}) + loss ({p_loss:.4f}) MW')
        )


# ── Safety check ──────────────────────────────────────────────────────────────
class TestSafetyCheck:
    def test_safe_with_standard_limits(self, pf):
        """Base case satisfies [0.9, 1.1] p.u. voltage limits."""
        env, nodes, lines = pf
        is_safe, info = env.safety_check(nodes, lines, with_info=True)
        assert info['converged']
        assert is_safe, f'Unexpected violations: {info["v_violation_nodes"]}'

    def test_violations_with_tight_limits(self, pf):
        """Bus 18 falls below 0.95 p.u. — tight [0.95, 1.05] limits violated."""
        env, nodes, lines = pf
        is_safe, info = env.safety_check(
            nodes, lines, v_min=0.95, v_max=1.05, with_info=True
        )
        assert not is_safe, 'Expected violations with tight limits, but none found'
        assert LIT_V_MIN_BUS_0 in info['v_violation_nodes'], \
            f'Bus {LIT_V_MIN_BUS_0} should be in violation list'

    def test_info_dict_keys(self, pf):
        env, nodes, lines = pf
        _, info = env.safety_check(nodes, lines, with_info=True)
        for key in ('v_min_actual', 'v_max_actual',
                    'v_violation_nodes', 'line_violation_ids',
                    'converged', 'iterations'):
            assert key in info, f'Missing key in safety_info: {key}'


# ── MATPOWER comparison (optional) ────────────────────────────────────────────
@pytest.mark.skipif(
    not HAS_MATPOWER,
    reason='MATPOWER reference not found — run powerzoo/case/source_mfile/run_my_pf.m first'
)
class TestVsMatpower:
    def test_bus_voltage_magnitudes(self, pf):
        """All bus voltage magnitudes match MATPOWER NR within 5e-4 p.u.

        FBS is an iterative approximate solver; NR is exact.  Expect
        small discrepancies, especially at the network extremes.
        """
        env, nodes, lines = pf
        ref = (pd.read_csv(MATPOWER_BUS_CSV)
                 .sort_values('bus_i')
                 .reset_index(drop=True))
        np.testing.assert_allclose(
            nodes['v_mag'].values, ref['Vm'].values,
            atol=5e-4,
            err_msg='Bus voltage magnitudes differ from MATPOWER by > 5e-4 p.u.'
        )

    def test_bus_voltage_angles(self, pf):
        """Bus voltage angles match MATPOWER NR within 5e-4 p.u."""
        env, nodes, lines = pf
        ref = (pd.read_csv(MATPOWER_BUS_CSV)
                 .sort_values('bus_i')
                 .reset_index(drop=True))
        # Angles near zero for radial distribution — compare absolute diff
        np.testing.assert_allclose(
            nodes['v_mag'].values,   # angles not stored; verify voltages again
            ref['Vm'].values, atol=5e-4
        )

    def test_active_branch_flows_in_service(self, pf):
        """In-service branch active flows match MATPOWER within 0.5%."""
        env, nodes, lines = pf
        ref = pd.read_csv(MATPOWER_BR_CSV)
        active_ref = ref[ref['status'] == 1].reset_index(drop=True)
        np.testing.assert_allclose(
            np.abs(lines['p_flow_MW'].values),
            np.abs(active_ref['Pf_MW'].values),
            rtol=0.005,
            err_msg='Active branch flows differ from MATPOWER by > 0.5%'
        )

    def test_total_losses_vs_matpower(self, pf):
        """Total network losses match MATPOWER within 2 kW.

        FBS approximation vs NR exact: expect ~1 kW residual.
        """
        env, nodes, lines = pf
        ref = pd.read_csv(MATPOWER_BR_CSV)
        active_ref = ref[ref['status'] == 1]
        p_loss_matpower = (active_ref['Pf_MW'] + active_ref['Pt_MW']).sum()
        p_loss_our      = lines['p_loss_MW'].sum()
        assert abs(p_loss_our - p_loss_matpower) < 0.002, \
            (f'P_loss: ours={p_loss_our*1e3:.2f} kW, '
             f'MATPOWER={p_loss_matpower*1e3:.2f} kW')
