"""
Power flow accuracy tests for Case123 (IEEE 123-bus three-phase distribution network).

Validates the three-phase BIBC/BCBV power flow implementation against:
  1. Physical invariants — slack bus voltage, per-phase angle convention,
     conservation laws, voltage unbalance factor (VUF < 2% per IEEE Std 1159)
  2. Regression reference — generated by draft/IEEE123_data_transform.py
     Saved to tests/ref_data/case123_nodes.csv, case123_lines.csv,
     and case123_summary.json

Run the reference generator before running this test suite:
    python draft/IEEE123_data_transform.py
"""
import json
import os

import numpy as np
import pandas as pd
import pytest

# ── Reference file paths ──────────────────────────────────────────────────────
REF_DIR          = os.path.join(os.path.dirname(__file__), 'ref_data')
REF_NODES_CSV    = os.path.join(REF_DIR, 'case123_nodes.csv')
REF_LINES_CSV    = os.path.join(REF_DIR, 'case123_lines.csv')
REF_SUMMARY_JSON = os.path.join(REF_DIR, 'case123_summary.json')
HAS_REFERENCE    = os.path.exists(REF_SUMMARY_JSON)

# ── Physical constants ────────────────────────────────────────────────────────
V_REF_MAG    = 1.05                 # substation reference voltage (p.u.)
V_REF_ANGLES = [0.0, -120.0, 120.0]  # phase A, B, C angles at slack (degrees)
VUF_LIMIT    = 2.0                  # IEEE Std 1159 VUF limit (%)


# ── Shared fixture ────────────────────────────────────────────────────────────
@pytest.fixture(scope='module')
def pf():
    """Run three-phase power flow once; share results across all tests."""
    from powerzoo.envs.grid.dist_3phase import DistGrid3PhaseEnv
    env = DistGrid3PhaseEnv()
    nodes, lines = env.cal_pf(df=True)
    is_safe, info = env.safety_check(nodes, lines, with_info=True)
    vuf_arr, max_vuf = env.calculate_vuf(nodes)
    return env, nodes, lines, info, max_vuf


# ── Convergence ───────────────────────────────────────────────────────────────
class TestConvergence:
    def test_converges(self, pf):
        env, nodes, lines, info, max_vuf = pf
        assert env._converged, 'Three-phase BFS did not converge'

    def test_iterations_in_range(self, pf):
        env, nodes, lines, info, max_vuf = pf
        assert 1 <= env._iterations <= 15, \
            f'Expected 1–15 iterations, got {env._iterations}'


# ── Slack bus ─────────────────────────────────────────────────────────────────
class TestSlackBus:
    def test_per_phase_voltage_magnitude(self, pf):
        """All three phases at slack bus must equal v_ref_mag = 1.05 p.u."""
        env, nodes, lines, info, max_vuf = pf
        for ph in 'ABC':
            v = float(nodes.iloc[0][f'V_{ph}'])
            np.testing.assert_allclose(
                v, V_REF_MAG, atol=1e-10,
                err_msg=f'Slack bus phase {ph}: {v:.8f} ≠ {V_REF_MAG}'
            )

    def test_per_phase_angles(self, pf):
        """Slack bus angles: A = 0°, B = -120°, C = +120°."""
        env, nodes, lines, info, max_vuf = pf
        for ph, expected in zip('ABC', V_REF_ANGLES):
            ang = float(nodes.iloc[0][f'angle_{ph}'])
            np.testing.assert_allclose(
                ang, expected, atol=1e-10,
                err_msg=f'Slack bus angle phase {ph}: {ang:.6f}° ≠ {expected}°'
            )

    def test_average_slack_voltage(self, pf):
        env, nodes, lines, info, max_vuf = pf
        np.testing.assert_allclose(
            nodes['v_mag'].iloc[0], V_REF_MAG, atol=1e-10
        )


# ── Bus voltages ──────────────────────────────────────────────────────────────
class TestBusVoltages:
    def test_all_per_phase_voltages_in_safe_range(self, pf):
        """All per-phase voltages within [0.8, 1.2] p.u. (Case123 Vmax/Vmin)."""
        env, nodes, lines, info, max_vuf = pf
        for ph in 'ABC':
            v = nodes[f'V_{ph}'].dropna().values
            assert np.all(v >= 0.8), \
                f'Phase {ph}: voltage below 0.8 p.u. at {np.where(v < 0.8)}'
            assert np.all(v <= 1.2), \
                f'Phase {ph}: voltage above 1.2 p.u. at {np.where(v > 1.2)}'

    def test_non_slack_voltages_at_most_vref(self, pf):
        """Passive network: non-slack buses cannot exceed reference voltage."""
        env, nodes, lines, info, max_vuf = pf
        for ph in 'ABC':
            v_non_slack = nodes[f'V_{ph}'].iloc[1:].dropna().values
            assert np.all(v_non_slack <= V_REF_MAG + 1e-6), \
                f'Phase {ph} has non-slack bus exceeding V_ref={V_REF_MAG}'

    def test_average_voltage_in_safe_range(self, pf):
        env, nodes, lines, info, max_vuf = pf
        v_avg = nodes['v_mag'].values
        assert np.all(v_avg >= 0.8)
        assert np.all(v_avg <= 1.2)

    def test_voltage_info_range_consistent(self, pf):
        """safety_info v_min/v_max matches actual node DataFrame values."""
        env, nodes, lines, info, max_vuf = pf
        all_v = np.concatenate(
            [nodes[f'V_{ph}'].dropna().values for ph in 'ABC']
        )
        np.testing.assert_allclose(info['v_min_actual'], all_v.min(), atol=1e-8)
        np.testing.assert_allclose(info['v_max_actual'], all_v.max(), atol=1e-8)


# ── Voltage unbalance factor ──────────────────────────────────────────────────
class TestVoltageUnbalance:
    def test_max_vuf_below_ieee_standard(self, pf):
        """IEEE Std 1159: VUF must be below 2% in normal operation."""
        env, nodes, lines, info, max_vuf = pf
        assert max_vuf < VUF_LIMIT, \
            f'Max VUF = {max_vuf:.4f}%  (limit: {VUF_LIMIT}%)'

    def test_vuf_array_length(self, pf):
        env, nodes, lines, info, max_vuf = pf
        vuf_arr, _ = env.calculate_vuf(nodes)
        assert len(vuf_arr) == env.n_nodes

    def test_all_vuf_non_negative(self, pf):
        env, nodes, lines, info, max_vuf = pf
        vuf_arr, _ = env.calculate_vuf(nodes)
        assert np.all(vuf_arr >= 0)

    def test_info_vuf_matches_calculate_vuf(self, pf):
        """safety_info max_vuf_percent must equal calculate_vuf() result."""
        env, nodes, lines, info, max_vuf = pf
        np.testing.assert_allclose(
            info['max_vuf_percent'], max_vuf, atol=1e-8
        )


# ── Line losses ───────────────────────────────────────────────────────────────
class TestLineLosses:
    def test_total_p_loss_positive(self, pf):
        env, nodes, lines, info, max_vuf = pf
        assert lines['p_loss_MW'].sum() > 0

    def test_total_q_loss_positive(self, pf):
        env, nodes, lines, info, max_vuf = pf
        assert lines['q_loss_MVAr'].sum() > 0

    def test_per_phase_p_losses_sum_to_total(self, pf):
        """Sum of phase A + B + C losses equals total column."""
        env, nodes, lines, info, max_vuf = pf
        p_phases = sum(lines[f'p_loss_{ph}_MW'].sum() for ph in 'ABC')
        p_total  = lines['p_loss_MW'].sum()
        np.testing.assert_allclose(p_phases, p_total, rtol=1e-6)

    def test_per_phase_q_losses_sum_to_total(self, pf):
        env, nodes, lines, info, max_vuf = pf
        q_phases = sum(lines[f'q_loss_{ph}_MVAr'].sum() for ph in 'ABC')
        q_total  = lines['q_loss_MVAr'].sum()
        np.testing.assert_allclose(q_phases, q_total, rtol=1e-6)

    def test_all_line_p_losses_non_negative(self, pf):
        """Each line's total three-phase active loss must be ≥ 0."""
        env, nodes, lines, info, max_vuf = pf
        assert np.all(lines['p_loss_MW'].values >= -1e-8)


# ── Safety check API ──────────────────────────────────────────────────────────
class TestSafetyCheck:
    def test_converged_flag_in_info(self, pf):
        env, nodes, lines, info, max_vuf = pf
        assert info['converged']

    def test_required_info_keys_present(self, pf):
        env, nodes, lines, info, max_vuf = pf
        required = (
            'v_min_actual', 'v_max_actual',
            'v_violation_nodes', 'line_violation_ids',
            'max_vuf_percent', 'converged', 'iterations',
        )
        for key in required:
            assert key in info, f'Missing key in safety_info: {key}'

    def test_no_violations_within_case_limits(self, pf):
        """Base case with V_ref=1.05 should satisfy [0.8, 1.2] limits."""
        env, nodes, lines, info, max_vuf = pf
        is_safe, tight_info = env.safety_check(
            nodes, lines, v_min=0.8, v_max=1.2, with_info=True
        )
        assert is_safe, \
            f'Unexpected violations: {tight_info["v_violation_nodes"]}'


# ── Regression vs reference ───────────────────────────────────────────────────
@pytest.mark.skipif(
    not HAS_REFERENCE,
    reason='Reference data not found — run draft/IEEE123_data_transform.py first'
)
class TestVsReference:
    def test_per_phase_voltage_regression(self, pf):
        """Per-phase bus voltages match stored reference within 1e-6 p.u."""
        env, nodes, lines, info, max_vuf = pf
        ref = pd.read_csv(REF_NODES_CSV, index_col=0)
        for ph in 'ABC':
            col = f'V_{ph}'
            np.testing.assert_allclose(
                nodes[col].values, ref[col].values,
                atol=1e-6,
                err_msg=f'Phase {ph} voltage regression failed'
            )

    def test_p_loss_regression(self, pf):
        """Total active loss matches stored reference within 1e-6 MW."""
        env, nodes, lines, info, max_vuf = pf
        with open(REF_SUMMARY_JSON) as f:
            ref = json.load(f)
        np.testing.assert_allclose(
            lines['p_loss_MW'].sum(), ref['p_loss_MW'], atol=1e-6
        )

    def test_q_loss_regression(self, pf):
        """Total reactive loss matches stored reference within 1e-6 MVAr."""
        env, nodes, lines, info, max_vuf = pf
        with open(REF_SUMMARY_JSON) as f:
            ref = json.load(f)
        np.testing.assert_allclose(
            lines['q_loss_MVAr'].sum(), ref['q_loss_MVAr'], atol=1e-6
        )

    def test_max_vuf_regression(self, pf):
        """Max VUF matches stored reference within 1e-4%."""
        env, nodes, lines, info, max_vuf = pf
        with open(REF_SUMMARY_JSON) as f:
            ref = json.load(f)
        np.testing.assert_allclose(
            max_vuf, ref['max_vuf_percent'], atol=1e-4
        )

    def test_per_phase_line_flows_regression(self, pf):
        """Per-phase line flows match stored reference within 1e-6 MW."""
        env, nodes, lines, info, max_vuf = pf
        ref = pd.read_csv(REF_LINES_CSV, index_col=0)
        for ph in 'ABC':
            col = f'P_{ph}_MW'
            if col in ref.columns:
                np.testing.assert_allclose(
                    lines[col].values, ref[col].values,
                    atol=1e-6,
                    err_msg=f'Phase {ph} line flow regression failed'
                )
